import { Problem } from './types';
import { generateId } from './storage';

export const SAMPLE_PROBLEMS: Problem[] = [
  {
    id: generateId(),
    title: 'Real-Time Traffic Congestion Prediction System',
    description: 'Major urban intersections experience severe congestion during peak hours, causing average delays of 45 minutes for commuters. Current signal systems are static and do not adapt to real-time flow. This leads to increased fuel consumption, air pollution, and productivity loss for thousands of daily commuters.',
    shortSummary: 'A transport problem: Urban intersections with static signals causing 45-min delays and high pollution during peak hours.',
    source: 'industry',
    domain: 'Transport',
    tags: ['data-driven', 'software', 'automation', 'iot'],
    difficulty: 'hard',
    urgency: 'high',
    status: 'published',
    affectedStakeholders: 'Daily commuters, logistics companies, emergency services',
    cause: 'Static signal timing not adapted to real-time traffic flow',
    impact: '45+ minute delays, increased pollution, productivity loss',
    frequency: 'Daily during peak hours (8–10 AM, 5–8 PM)',
    feasibility: 'medium',
    requiredSkills: ['Machine Learning', 'IoT', 'Data Analysis', 'Python'],
    requiredResources: ['Traffic camera feed API', 'Historical congestion data', 'GPU compute'],
    confidenceScore: 91,
    isConfidential: false,
    submittedBy: 'Arjun Mehta',
    submittedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'Admin',
    reviewedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Well-scoped, good data availability, suitable for ML track students.',
    rawInput: { title: 'Real-Time Traffic Congestion', description: 'Static signals causing delays' },
    aiExtracted: true,
    duplicateWarning: false,
    organizationName: 'SmartCity Solutions Pvt. Ltd',
  },
  {
    id: generateId(),
    title: 'Automated Student Attendance & Analytics Portal',
    description: 'Our college currently uses paper-based attendance registers which are error-prone, time-consuming and difficult to analyze. Faculty spend 10–15 minutes per class taking attendance manually. There is no way to identify at-risk students early or send automated alerts to parents when attendance drops below threshold.',
    shortSummary: 'A campus problem: Paper attendance registers waste 15 min/class and prevent early identification of at-risk students.',
    source: 'campus',
    domain: 'Education',
    tags: ['campus', 'software', 'automation', 'data-driven'],
    difficulty: 'medium',
    urgency: 'medium',
    status: 'published',
    affectedStakeholders: 'Students, faculty, parents, academic administration',
    cause: 'Paper-based manual attendance with no digital integration',
    impact: '10–15 min wasted per class, delayed parent notifications, no early warning system',
    frequency: 'Every class session, 6 days a week',
    feasibility: 'high',
    requiredSkills: ['Web Development', 'Database Design', 'Mobile Development'],
    requiredResources: ['College WiFi network', 'Student database access', 'SMS API'],
    confidenceScore: 88,
    isConfidential: false,
    submittedBy: 'Prof. Lakshmi Devi',
    submittedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'Admin',
    reviewedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Classic campus problem. High feasibility. Recommend QR or RFID approach.',
    rawInput: { title: 'Student Attendance Portal', description: 'Paper-based attendance issues' },
    aiExtracted: true,
    duplicateWarning: false,
    organizationName: 'MVJ College of Engineering',
  },
  {
    id: generateId(),
    title: 'Clean Drinking Water Access Monitoring in Rural Villages',
    description: 'In rural districts, borewells and community water tanks frequently malfunction without any monitoring system. Villagers often travel 3–5 km to access clean water when local sources fail. NGO volunteers manually check each water point monthly, creating gaps in data and delayed response to failures.',
    shortSummary: 'A social impact problem: Unmonitored rural water sources cause 3–5 km travel hardship with monthly-only manual checks.',
    source: 'ngo',
    domain: 'Environment',
    tags: ['iot', 'hardware', 'ngo', 'monitoring', 'data-driven'],
    difficulty: 'hard',
    urgency: 'critical',
    status: 'published',
    affectedStakeholders: 'Rural communities (~2,000 families), NGO field workers, district health officers',
    cause: 'No real-time monitoring of borewell and water tank status',
    impact: '3–5 km water collection trips, health risks from contaminated alternatives',
    frequency: 'Failures occur 4–6 times per year per borewell; each undetected for weeks',
    feasibility: 'medium',
    requiredSkills: ['IoT', 'Data Analysis', 'Mobile Development', 'Python'],
    requiredResources: ['Water level sensors', 'GSM modules', 'Solar power units', 'Field access'],
    confidenceScore: 94,
    isConfidential: false,
    submittedBy: 'Ravi Kumar (WaterWatch NGO)',
    submittedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'Admin',
    reviewedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'High social impact. Field collaboration available. Excellent for hardware+software team.',
    rawInput: { title: 'Rural water monitoring', description: 'Borewell failures undetected' },
    aiExtracted: true,
    duplicateWarning: false,
    organizationName: 'WaterWatch NGO',
    location: 'Tumkur District, Karnataka',
  },
  {
    id: generateId(),
    title: 'Hospital Bed Availability Real-Time Dashboard',
    description: 'During emergencies and peak patient inflow, hospitals waste critical time manually calling departments to check bed availability. Patients in the ER wait 30–90 minutes just for a bed assignment, worsening outcomes for critical cases. No centralized visibility exists across wards.',
    shortSummary: 'A healthcare problem: Manual bed checks cause 30–90 min ER wait times with no cross-ward visibility.',
    source: 'industry',
    domain: 'Healthcare',
    tags: ['healthcare', 'software', 'data-driven', 'web'],
    difficulty: 'medium',
    urgency: 'critical',
    status: 'under_review',
    affectedStakeholders: 'Emergency patients, ER doctors, hospital administration, nurses',
    cause: 'No digital bed management system across hospital departments',
    impact: '30–90 minute delays for critical patients, poor resource utilization',
    frequency: 'Daily — 40+ emergency cases per day',
    feasibility: 'high',
    requiredSkills: ['Web Development', 'Database Design', 'UI/UX Design'],
    requiredResources: ['Hospital IT infrastructure access', 'Real-time database'],
    confidenceScore: 82,
    isConfidential: true,
    submittedBy: 'Dr. Priya Sharma',
    submittedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    rawInput: { title: 'Hospital bed availability', description: 'Manual bed checks in ER' },
    aiExtracted: true,
    duplicateWarning: false,
    organizationName: 'Apollo Hospital',
  },
  {
    id: generateId(),
    title: 'E-Waste Collection and Recycling Awareness Platform',
    description: 'Electronic waste is growing at 3x the rate of general waste in Indian cities. Most households and small offices dispose e-waste in regular bins or dump sites, contaminating soil and groundwater with heavy metals. There is no easy way for citizens to find certified e-waste collection points or schedule pickups.',
    shortSummary: 'An environment problem: Citizens cannot locate e-waste collection points, leading to hazardous dumping in landfills.',
    source: 'general',
    domain: 'Environment',
    tags: ['environment', 'software', 'mobile', 'awareness', 'civic-issues'],
    difficulty: 'easy',
    urgency: 'medium',
    status: 'published',
    affectedStakeholders: 'Urban households, small businesses, recycling companies, municipal corporations',
    cause: 'Lack of accessible information about e-waste disposal and collection infrastructure',
    impact: 'Heavy metal contamination of soil and water; health risks for informal recyclers',
    frequency: 'Ongoing — 3 million tonnes of e-waste generated annually in India',
    feasibility: 'high',
    requiredSkills: ['Mobile Development', 'Web Development', 'UI/UX Design'],
    requiredResources: ['Google Maps API', 'E-waste collector database', 'Government open data'],
    confidenceScore: 79,
    isConfidential: false,
    submittedBy: 'Sneha Patel',
    submittedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'Admin',
    reviewedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Clear problem. Good starting point for beginners. Maps integration is the core challenge.',
    rawInput: { title: 'E-waste platform', description: 'Citizens cannot find collection points' },
    aiExtracted: true,
    duplicateWarning: false,
  },
  {
    id: generateId(),
    title: 'Farm Input Cost Predictor for Small Farmers',
    description: 'Small and marginal farmers in Karnataka over-spend on seeds, fertilizers and pesticides due to lack of price visibility and crop-specific guidance. Input costs have risen 60% in 5 years while crop prices remain volatile. Farmers rely on word-of-mouth from equipment dealers who often push high-margin products.',
    shortSummary: 'An agriculture problem: Small farmers overspend on inputs due to price opacity and biased dealer advice.',
    source: 'ngo',
    domain: 'Agriculture',
    tags: ['data-driven', 'mobile', 'education', 'ngo'],
    difficulty: 'medium',
    urgency: 'high',
    status: 'published',
    affectedStakeholders: 'Small and marginal farmers, agricultural extension officers, FPOs',
    cause: 'No digital tool for comparing input prices and getting crop-specific recommendations',
    impact: '30–40% over-expenditure on inputs reducing net income by ₹15,000–40,000/season',
    frequency: 'Every planting season (2–3 times a year)',
    feasibility: 'medium',
    requiredSkills: ['Mobile Development', 'Data Analysis', 'Machine Learning', 'Python'],
    requiredResources: ['AGMARKNET price data API', 'Soil database', 'Multilingual NLP support'],
    confidenceScore: 85,
    isConfidential: false,
    submittedBy: 'Krishnamurthy B. (FarmAid Foundation)',
    submittedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'Admin',
    reviewedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Needs Kannada/Telugu language support. Strong social impact potential.',
    rawInput: { title: 'Farm input predictor', description: 'Small farmers overspend on inputs' },
    aiExtracted: true,
    duplicateWarning: false,
    organizationName: 'FarmAid Foundation',
    location: 'Hassan, Karnataka',
  },
  {
    id: generateId(),
    title: 'Reddit: Freelancers Cannot Track Invoice Payments Easily',
    description: 'Multiple Reddit threads on r/freelance highlight a persistent issue: freelancers lose track of outstanding invoices, forget follow-up dates, and have no unified view of their payment status across multiple clients. Existing accounting tools are expensive or too complex for solo freelancers.',
    shortSummary: 'A technology problem extracted from Reddit: Freelancers lack a simple, affordable invoice tracking and follow-up tool.',
    source: 'online',
    domain: 'Finance',
    tags: ['software', 'productivity', 'web', 'mobile'],
    difficulty: 'easy',
    urgency: 'medium',
    status: 'submitted',
    affectedStakeholders: 'Freelancers, independent contractors, small agencies',
    cause: 'High cost and complexity of existing invoicing tools targeting enterprise users',
    impact: 'Late payments, cash flow issues, administrative burden for freelancers',
    frequency: 'Reported as ongoing issue across thousands of freelancers',
    feasibility: 'high',
    requiredSkills: ['Web Development', 'Mobile Development', 'UI/UX Design'],
    requiredResources: ['Email API', 'Payment gateway integration'],
    confidenceScore: 72,
    isConfidential: false,
    submittedBy: 'System (Reddit Crawl)',
    submittedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    sourceUrl: 'https://www.reddit.com/r/freelance/',
    rawInput: { title: 'Freelancer invoice tracking', description: 'Cannot track invoice payments' },
    aiExtracted: true,
    duplicateWarning: false,
  },
  {
    id: generateId(),
    title: 'Lab Equipment Scheduling & Maintenance Tracker',
    description: 'Engineering college labs suffer from unplanned equipment breakdowns and double-booking of expensive instruments (oscilloscopes, spectrum analyzers). No booking system exists — students and faculty face conflict and downtime. Maintenance logs are kept in physical notebooks, frequently lost.',
    shortSummary: 'A campus problem: Lab equipment is double-booked and maintenance logs are paper-based, causing downtime and conflict.',
    source: 'campus',
    domain: 'Education',
    tags: ['campus', 'software', 'automation', 'web'],
    difficulty: 'easy',
    urgency: 'low',
    status: 'published',
    affectedStakeholders: 'Students, lab technicians, faculty, department heads',
    cause: 'No digital booking or maintenance tracking system for lab equipment',
    impact: 'Equipment conflicts, unexpected breakdowns, wasted lab hours',
    frequency: 'Multiple conflicts per week; major breakdowns 2–3 times per semester',
    feasibility: 'high',
    requiredSkills: ['Web Development', 'Database Design', 'UI/UX Design'],
    requiredResources: ['College intranet access', 'Equipment inventory list'],
    confidenceScore: 90,
    isConfidential: false,
    submittedBy: 'Dr. Suresh (HOD, ECE)',
    submittedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    reviewedBy: 'Admin',
    reviewedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    reviewNotes: 'Perfect beginner project. Can be tested and deployed within the campus itself.',
    rawInput: { title: 'Lab scheduling tracker', description: 'No booking system for equipment' },
    aiExtracted: true,
    duplicateWarning: false,
    organizationName: 'MVJ College — ECE Department',
  },
];
